### ISSUE TITLE
Trying to generate `today` data on last day of the month generates full day.

### ISSUE THREAD

**Issue by lcouzens** [project-koku/nise#104]
When using `today` with static reports to generate current day data, it seems on the last day of the month we generate a full day instead of to the current hour.

```
---
generators:
  - OCPGenerator:
      start_date: today
      nodes:
        - node:
          node_name: ocp-tiers
          cpu_cores: 5
          memory_gig: 5
          resource_id: 11995555
          namespaces:
            ocp_tiers:
              pods:
                - pod:
                  pod_name: tiers
                  cpu_request: 2
                  mem_request_gig: 3
                  cpu_limit: 4
                  mem_limit_gig: 4
                  pod_seconds: 3600
                  cpu_usage:
                    full_period: 3
                  mem_usage_gig:
                    full_period: 2
                  labels: label_app:teirs
              volumes:
                - volume:
                  volume_name: pvc-volume_1
                  storage_class: gp2
                  volume_request_gig: 4
                  labels: label_volume:tiers
                  volume_claims:
                  - volume_claim:
                    volume_claim_name: data_tiers
                    pod_name: tiers
                    labels: label_volume:stor_tiers
                    capacity_gig: 10
                    volume_claim_usage_gig:
                      full_period: 5
```
