### ISSUE TITLE
Bug - Resource_ID not working correctly with RDSGenerators in static yamls

### ISSUE THREAD

**Issue by lcouzens** [project-koku/nise#120]
When generating AWS RDS data using nise if you set a resource id it seems to get ignored. Looking at the generated CSV shows a new resource id for each line item.

When asserting raw values this throws off the expected distinct count value.

Static yaml:
```
---
generators:
  - RDSGenerator:
      start_date: today
      processor_arch: 64-bit
      resource_id: 99995555
      product_sku: VEAJHRNKTJZB
      region: us-west-1a
      tags:
        resourceTags/user:openshift_node: ocp-nod
      instance_type:
        inst_type: db.t3.medium
        vcpu: 2
        memory: '4 GiB'
        storage: 'EBS Only'
        family: 'Memory Optimized'
        cost: 1.000
        rate: 0.500

accounts:
  payer: 9999999999999
  user:
    - 9999999999999
```

csv snippet showing different resource id's per line.

![Screenshot from 2019-07-30 15-17-37](https://user-images.githubusercontent.com/18352403/62138081-f4bcab80-b2de-11e9-8282-eeb18031ed6f.png)
