### ISSUE TITLE
Nise generation seems to create a bad capacity data for memory

### ISSUE THREAD

**Issue by lcouzens** [project-koku/nise#65]
Seems that the data generated for memory capacity seems extremely low compared to usage/limit/request.

![screenshot from 2019-01-18 23-11-29](https://user-images.githubusercontent.com/18352403/51690321-5e869080-1ff0-11e9-9b6d-23236ff36144.png)

**Comment by lcouzens** [comment]
Bumping this a little now we have static reporting. That being said this seems to be totally broken with static reports. It's also possible we might be doing some strange with the data somewhere. Either way we should investigate this soon.

Here's my static report and UI screenshot after ingestion:
```
---
generators:
  - OCPGenerator:
      start_date: 2-4-2019
      end_date: 2-11-2019
      nodes:
        - node:
          node_name: alpha
          cpu_cores: 4
          memory_gig: 4
          resource_id: 55555555
          namespaces:
            custom-test:
              pods:
                - pod:
                  pod_name: porky
                  cpu_request: 2
                  mem_request: 2
                  cpu_limit: 4
                  mem_limit: 4
                  pod_seconds: 3600
                  labels: wef_key:wef_value|pok_key:pok_value
```
![screenshot from 2019-02-11 11-04-23](https://user-images.githubusercontent.com/18352403/52559652-cf4deb00-2ded-11e9-971a-adbb385f223e.png)
