### ISSUE TITLE
Static reports not generating S3 data for previous month when specifiying `last_month` as start_date

### ISSUE THREAD

**Issue by lcouzens** [project-koku/nise#94]
1. Generate static data using the following report
2. See previous month data has no S3 lines

We expect to see S3 data for the full two month period

```
---
generators:
  - EC2Generator:
      start_date: last_month
      processor_arch: 32-bit
      resource_id: 55555555
      product_sku: VEAJHRNKTJZQ
      region: us-east-1a
      instance_type:
        inst_type: m5.large
        vcpu: 2
        memory: '8 GiB'
        storage: 'EBS Only'
        family: 'General Purpose'
        cost: 1.000
        rate: 0.500
  - S3Generator:
      product_sku: VEAJHRNAAAAA
      amount: 10
      rate: 3

accounts:
  payer: 9999999999999
  user:
    - 9999999999999
```
